// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBirsZQmueRyb3l4nUEuY-EHy6veZkihr4',
    appId: '1:768501477878:web:44f7ca3e0f713442d757d7',
    messagingSenderId: '768501477878',
    projectId: 'feedback-project-a40ba',
    authDomain: 'feedback-project-a40ba.firebaseapp.com',
    storageBucket: 'feedback-project-a40ba.appspot.com',
    measurementId: 'G-NVT49L49CG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8FZkHKfdh4Q_q7FGLl1vm0zcTG7LL5t4',
    appId: '1:768501477878:android:39074af3e5e1910fd757d7',
    messagingSenderId: '768501477878',
    projectId: 'feedback-project-a40ba',
    storageBucket: 'feedback-project-a40ba.appspot.com',
  );
}
