// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABhzveUEF2tO6XZGC5F-5hAJ22Y_bER5s',
    appId: '1:1088703444514:web:b83409e001bcda6ac93c7b',
    messagingSenderId: '1088703444514',
    projectId: 'music-pad-9dcc8',
    authDomain: 'music-pad-9dcc8.firebaseapp.com',
    storageBucket: 'music-pad-9dcc8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC359scnmPNf1JwLIfFBtorLqf6v7BgNi4',
    appId: '1:1088703444514:android:ea2c7150efa20609c93c7b',
    messagingSenderId: '1088703444514',
    projectId: 'music-pad-9dcc8',
    storageBucket: 'music-pad-9dcc8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7sOn-1IiHDXaBKc1UjrPK0u76PcLOZl0',
    appId: '1:1088703444514:ios:4da2239ffbc90020c93c7b',
    messagingSenderId: '1088703444514',
    projectId: 'music-pad-9dcc8',
    storageBucket: 'music-pad-9dcc8.appspot.com',
    iosBundleId: 'com.example.musicpad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7sOn-1IiHDXaBKc1UjrPK0u76PcLOZl0',
    appId: '1:1088703444514:ios:63a22efaae7d325ac93c7b',
    messagingSenderId: '1088703444514',
    projectId: 'music-pad-9dcc8',
    storageBucket: 'music-pad-9dcc8.appspot.com',
    iosBundleId: 'com.example.musicpad.RunnerTests',
  );
}
